const Q = [

    { "level":0, "tecnica":"Are Makki", "video":"y3nUBMaMIgw", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"Montong makki", "video":"5dpFzb5eges", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"Montong an makki", "video":"5fkuhw3ykeE", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"Olgul makki", "video":"eLmvdSATImQ", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"Montong bakat makki", "video":"FJHvYN50-K0", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"sonnal montong maki", "video":"FJHvYN50-K0", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"jansonnal montong bakat maki", "video":"vYhSC67r93o", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"nulo maki", "video":"hWcDlF0r8DM", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"olgul bakat maki", "video":"IuvzhF7rfKk", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"gechio are maki", "video":"pmtJV1w_Q0", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"batagson monton an makki", "video":"dYO7moC38vI", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"sonnal are makki", "video":"V6WI_u9WPJA", "alt": "", "picture": "are-makki" },   
    { "level":0, "tecnica":"gehio montong makki", "video":"f0wssE3FkYQ", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"okgoro are makki", "video":"mVd6rud9Wjc", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"jansonnal montong yop makki", "video":"Lcs_rJEHvAw", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"goduro montong makki", "video":"jDuPHXcKiXs", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"goduro are makki", "video":"YjJmEHA62Ck", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"Mongtong bande jirugui", "video":"ArcCBvkyLA4", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"Mongtong baro jirugui", "video":"zwvB31_dC_k", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"ogul bande jirugui", "video":"Jpst_GappfM", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"Dubong montong jirugui", "video":"FznywtUJlJ8", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"pionson kut seuo chirugui", "video":"Mu6_Lui_ip4", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"dung chumok ape chigui", "video":"l4KM6HRNB48", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"me chumok ape chigui", "video":"", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"palkup dollyo chigui", "video":"kenoYzX61zo", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"du checho jirugui", "video":"aI-HSZCWGyc", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"dung chumok bakat chigui", "video":"MW-Pfo0CDMI", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"yop jirugui", "video":"gbsfs9E3NI0", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"chebipum mok chigui", "video":"_vaC0DUpohg", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"montong piochok palkup chigi", "video":"WUPBPPUYWT0", "alt": "PALKUT MONTONG PIOCHOk CHIGUI", "picture": "are-makki" },
    { "level":0, "tecnica":"bituro jansonnal olgul backat makki", "video":"2ceqGSwbm8M", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"bochumok chumbi", "video":"", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"gawi makki", "video":"zjiPglLsdOY", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"dangkiok ollyo murop chigui", "video":"4igah7sddqQ", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"oe santul makki", "video":"c0sDiHSDg0w", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"dangkiok tok jirugui", "video":"ZbOd9D6RdYw", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"ap chagui", "video":"G8KCx2g1nfs", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"dollyo chagui", "video":"mY-lCnt12Ck", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"yop chagui", "video":"vHFKx2jRcCU", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"tuit chagui", "video":"Jdgnmr9enu8", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"nakko chagui", "video":"HaSC6PZzw0U", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"furio chagui", "video":"3QRqe15zIKE", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"neryo chagui", "video":"524tqlcNlJk", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"mom dollyo yop chagui", "video":"zXnz75Wh308", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"mon dollyo tuit chagui", "video":"XFsQVojlQ58", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"mom dollyo nakko chagui", "video":"z_9Cv3DXcJU", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"mom dollyo furio chagui", "video":"m0eF69SfcPY", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"bandal chagui", "video":"YExkwhssI9k", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"tuio bandal chagui", "video":"DxDCg_6v9rE", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"tuio ap chagui", "video":"Z9rnJ15KKCU", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"bakat chagui", "video":"5hEZJ_Y22e0", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"Tuio dollyo chagui", "video":"DmnCfnC7qeM", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"Tuio tuit chagui", "video":"C5rBfYD15p4", "alt": "", "picture": "are-makki" },
    { "level":0, "tecnica":"an chagui", "video":"iO-Py_LDQYM", "alt": "", "picture": "are-makki" }

];

export default Q;